# requirements.yml (Ansible roles)
---
roles:
  # Security hardening role
  - name: geerlingguy.security
    version: "2.0.1"

  # Docker installation role
  - name: geerlingguy.docker
    version: "7.1.0"

  # Pip installation role
  - name: geerlingguy.pip
    version: "2.2.0"

  # NTP role for time synchronization
  - name: geerlingguy.ntp
    version: "2.3.0"

  # Node exporter for Prometheus monitoring
  - name: cloudalchemy.node_exporter
    version: "3.2.0"

  # Prometheus server role
  - name: cloudalchemy.prometheus
    version: "2.25.0"

  # Grafana role
  - name: cloudalchemy.grafana
    version: "0.23.1"

  # Firewall management
  - name: geerlingguy.firewall
    version: "2.4.0"