# requirements.yml
---
roles:
  # Security hardening role
  - name: geerlingguy.security
    version: "2.0.1"

  # Docker installation role
  - name: geerlingguy.docker
    version: "7.1.0"

  # Pip installation role
  - name: geerlingguy.pip
    version: "2.2.0"

  # NTP role for time synchronization
  - name: geerlingguy.ntp
    version: "2.3.0"

  # Node exporter for Prometheus monitoring - FIX: Use available version
  - name: cloudalchemy.node_exporter
    version: "2.0.0"  # Changed from 3.2.0 to 2.0.0

  # Prometheus server role - These versions may also need updating
  - name: cloudalchemy.prometheus
    version: "2.25.0"  # This might also need version verification

  # Grafana role - This version may also need updating
  - name: cloudalchemy.grafana
    version: "0.23.1"  # This might also need version verification

  # Firewall management
  - name: geerlingguy.firewall
    version: "2.4.0"