# molecule/default/molecule.yml
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

driver:
  name: docker

platforms:
  - name: controller-01
    image: quay.io/rockylinux/rockylinux:9
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    groups:
      - control
      - network
      - monitoring

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer
      stdout_callback: yaml
  inventory:
    group_vars:
      all:
        kolla_base_distro: rocky
        kolla_tag: "2024.2"
        enable_proxysql: "yes"
    host_vars:
      controller-01:
        ansible_connection: docker

verifier:
  name: testinfra
  options:
    verbose: true
    
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy