# Focused Traditional Compute with Specific Services - globals.yml
---

#######################
# Basic Configuration
#######################
kolla_base_distro: "debian"
openstack_release: "2025.1"
kolla_tag: "2025.1"
kolla_container_engine: "docker"

#######################
# Network Configuration
#######################
network_interface: "ens33"
neutron_external_interface: "ens35"
kolla_internal_vip_address: "10.10.27.250"
kolla_external_vip_address: "10.10.28.250"

# TLS Configuration
kolla_enable_tls_external: "no"
kolla_enable_tls_internal: "no"
kolla_external_fqdn: "openstack.region.com"

#######################
# Critical 2025.1 Fixes
#######################
keystone_wsgi_provider: "apache"
cinder_wsgi_provider: "uwsgi"
nova_wsgi_provider: "apache"
placement_wsgi_provider: "apache"

# RabbitMQ 4.0 migration requirements
om_enable_queue_manager: true
om_enable_rabbitmq_quorum_queues: true
om_enable_rabbitmq_transient_quorum_queue: true
om_enable_rabbitmq_stream_fanout: true

# Database load balancing
enable_proxysql: "no"

#######################
# Core OpenStack Services
#######################
enable_keystone: "yes"
enable_glance: "yes"
enable_nova: "yes"
enable_neutron: "yes"
enable_horizon: "no"  # Disabled per your request
enable_cinder: "yes"
enable_placement: "yes"

#######################
# Database and Messaging
#######################
enable_mariadb: "yes"
enable_rabbitmq: "yes"
enable_memcached: "yes"
enable_redis: "yes"
enable_haproxy: "yes"        # Enabled per your request
enable_keepalived: "yes"     # Enabled per your request

#######################
# Requested Advanced Services
#######################
enable_masakari: "yes"        # Temporarily disabled due to config issue
enable_watcher: "yes"        # Resource Optimization
enable_skyline: "yes"        # Modern Web UI

# Skyline Configuration
skyline_apiserver_port: "9998"
skyline_console_port: "9997"

#######################
# Explicitly Disable Unwanted Services
#######################
enable_ironic: "no"
enable_ironic_inspector: "no"
enable_ironic_neutron_agent: "no"
enable_octavia: "yes"
enable_prometheus: "yes"
enable_grafana: "yes"
enable_elasticsearch: "no"
enable_kibana: "no"
enable_opensearch: "no"
enable_opensearch_dashboards: "no"

#######################
# Traditional Nova Compute
#######################
enable_nova_compute: "yes"
nova_compute_virt_type: "kvm"

#######################
# Octavia Configuration
#######################
# Load balancer as a service
octavia_amp_network:
  name: lb-mgmt-net
  provider_network_type: "geneve"
  cidr: "10.11.28.0/24"
  allocation_pool_start: "10.11.28.100"
  allocation_pool_end: "10.11.28.140"
  gateway_ip: "10.11.28.1"
  enable_dhcp: true
  subnet:
    name: lb-mgmt-subnet
    cidr: "10.11.28.0/24"
    allocation_pool_start: "10.11.28.100"
    allocation_pool_end: "10.11.28.140"
    gateway_ip: "10.11.28.1"
    enable_dhcp: true

#######################
# Masakari Configuration
#######################
# These will be auto-set by enable_masakari: "yes"
# enable_masakari_instancemonitor: "{{ enable_masakari | bool }}"
# enable_masakari_hostmonitor: "{{ enable_masakari | bool }}"

# Additional configuration if needed
masakari_coordination_backend: "redis"
masakari_wsgi_provider: "apache"

#######################
# Watcher Configuration
#######################
watcher_database_name: "watcher"
watcher_database_user: "watcher"

#######################
# OVN Networking Configuration
#######################
neutron_plugin_agent: "ovn"
enable_openvswitch: "yes"
enable_ovn: "yes"

# OVN specific settings
neutron_ovn_distributed_fip: "yes"
neutron_ovn_dhcp_agent: "yes"
enable_ovn_sb_db_relay: "no"

# OVN controller configuration
ovn_controller_ovn_remote: "tcp:{{ kolla_internal_vip_address }}:6642"
ovn_controller_ovn_encap_type: "geneve"
ovn_controller_ovn_encap_ip: "{{ ansible_host }}"

# Physical network mappings for OVN
neutron_ovn_bridge_mappings:
  - "physnet1:br-ex"

#######################
# External Ceph Configuration
#######################
enable_ceph: "no"
glance_backend_ceph: "yes"
cinder_backend_ceph: "yes"
nova_backend_ceph: "yes"

# External Ceph cluster configuration
ceph_nova_user: "nova"
ceph_nova_keyring: "ceph.client.nova.keyring"
ceph_cinder_user: "cinder"
ceph_cinder_keyring: "ceph.client.cinder.keyring"
ceph_cinder_backup_user: "cinder-backup"
ceph_cinder_backup_keyring: "ceph.client.cinder-backup.keyring"
ceph_glance_user: "glance"
ceph_glance_keyring: "ceph.client.glance.keyring"

# Ceph RBD pool names
ceph_nova_pool_name: "vms"
ceph_cinder_pool_name: "volumes"
ceph_cinder_backup_pool_name: "backups"
ceph_glance_pool_name: "images"

# RBD secret UUIDs
cinder_rbd_secret_uuid: "{{ nova_rbd_secret_uuid }}"
nova_rbd_secret_uuid: "4049ba20-c583-4c49-a8c4-62397d477f96"
rbd_secret_uuid: "{{ nova_rbd_secret_uuid }}"

#######################
# Performance Optimization
#######################
openstack_logging_debug: "False"
enable_central_logging: "yes"
