# config/kolla/globals.yml.example
---
# Kolla-Ansible 2024.2 Configuration Template
# Basic Configuration
kolla_base_distro: "rocky"
openstack_release: "2024.2"
kolla_tag: "2024.2"
kolla_container_engine: "docker"

# Network Configuration
network_interface: "ens33"
neutron_external_interface: "ens35"
kolla_internal_vip_address: "10.10.27.250"
kolla_external_vip_address: "10.10.28.250"

# Enable TLS
kolla_enable_tls_external: "no"
kolla_enable_tls_internal: "no"
kolla_external_fqdn: "openstack.region.com"

# Core OpenStack Services
enable_keystone: "yes"
enable_glance: "yes"
enable_nova: "yes"
enable_neutron: "yes"
enable_horizon: "yes"
enable_cinder: "yes"

# Advanced Services
enable_octavia: "yes"
enable_ironic: "yes"
enable_masakari: "yes"
enable_watcher: "yes"

# Ironic Configuration
enable_ironic_inspector: "yes"
enable_ironic_pxe_uefi: "yes"
ironic_dnsmasq_interface: "{{ network_interface }}"
ironic_dnsmasq_dhcp_ranges:
  - network: "10.10.27.0/24"
    start: "10.10.27.50"
    end: "10.10.27.100"
    gateway: "10.10.27.1"
ironic_dnsmasq_default_gateway: "10.10.27.1"
ironic_dnsmasq_dns_servers: "8.8.8.8,8.8.4.4"
ironic_cleaning_network: "public1"
ironic_provisioning_network: "public1"

# Monitoring and Logging
enable_prometheus: "yes"
enable_grafana: "yes"
enable_elasticsearch: "yes"
enable_kibana: "yes"

# Prometheus Configuration
prometheus_haproxy_user: "admin"
prometheus_haproxy_password: "{{ keystone_admin_password }}"
prometheus_alertmanager_user: "admin" 
prometheus_alertmanager_password: "{{ keystone_admin_password }}"

# Enable Prometheus exporters
enable_prometheus_mysqld_exporter: "yes"
enable_prometheus_memcached_exporter: "yes"
enable_prometheus_alertmanager: "yes"
enable_prometheus_openstack_exporter: "yes"
enable_prometheus_elasticsearch_exporter: "yes"
enable_prometheus_blackbox_exporter: "yes"
enable_prometheus_libvirt_exporter: "yes"

# Database and Messaging
enable_mariadb: "yes"
enable_proxysql: "yes"
enable_rabbitmq: "yes"
enable_memcached: "yes"

# Kolla-Ansible 2024.2 Features
om_enable_rabbitmq_transient_quorum_queue: true
om_enable_rabbitmq_stream_fanout: true

# External Ceph Configuration
enable_ceph: "no"
glance_backend_ceph: "yes"
cinder_backend_ceph: "yes"
nova_backend_ceph: "yes"
gnocchi_backend_storage: "ceph"

# External Ceph cluster configuration
ceph_nova_user: "nova"
ceph_nova_keyring: "ceph.client.nova.keyring"
ceph_cinder_user: "cinder"
ceph_cinder_keyring: "ceph.client.cinder.keyring"
ceph_cinder_backup_user: "cinder-backup"
ceph_cinder_backup_keyring: "ceph.client.cinder-backup.keyring"
ceph_glance_user: "glance"
ceph_glance_keyring: "ceph.client.glance.keyring"
ceph_gnocchi_user: "gnocchi"
ceph_gnocchi_keyring: "ceph.client.gnocchi.keyring"

# Ceph RBD pool names (adjust to match your Ceph cluster)
ceph_nova_pool_name: "vms"
ceph_cinder_pool_name: "volumes"
ceph_cinder_backup_pool_name: "backups"
ceph_glance_pool_name: "images"
ceph_gnocchi_pool_name: "gnocchi"

# RBD secret UUIDs (generate with uuidgen)
cinder_rbd_secret_uuid: "{{ nova_rbd_secret_uuid }}"
nova_rbd_secret_uuid: "4049ba20-c583-4c49-a8c4-62397d477f96"
rbd_secret_uuid: "{{ nova_rbd_secret_uuid }}"

# OVN Networking
neutron_plugin_agent: "ovn"
neutron_ovn_distributed_fip: "yes"
neutron_ovn_dhcp_agent: "yes"

# Security
keystone_token_provider: "fernet"
keystone_fernet_token_expiry: 3600