# inventories/development/hosts.yml
---
all:
  children:
    control:
      hosts:
        controller-01:
          ansible_host: 10.0.0.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        controller-02:
          ansible_host: 10.0.0.11
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        controller-03:
          ansible_host: 10.0.0.12
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    network:
      hosts:
        controller-01:
        controller-02:
        controller-03:

    compute:
      hosts:
        compute-01:
          ansible_host: 10.0.0.20
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        compute-02:
          ansible_host: 10.0.0.21
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    storage:
      hosts:
        storage-01:
          ansible_host: 10.0.0.30
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        storage-02:
          ansible_host: 10.0.0.31
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    monitoring:
      hosts:
        controller-01:
        controller-02:
        controller-03:

    deployment:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
