# inventories/development/hosts.yml
---
all:
  children:
    control:
      hosts:
        ka-ctl1:
          ansible_host: 10.10.27.200
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ka-ctl2:
          ansible_host: 10.10.27.201
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ka-ctl3:
          ansible_host: 10.10.27.202
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    network:
      hosts:
        ka-net1:
          ansible_host: 10.10.27.203
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ka-net2:
          ansible_host: 10.10.27.204
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    compute:
      hosts:
        ka-hv1:
          ansible_host: 10.10.27.212
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ka-hv2:
          ansible_host: 10.10.27.213
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    storage:
      hosts:
        ka-str1:
          ansible_host: 10.10.27.206
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    monitoring:
      hosts:
        ka-ctl1:
          ansible_host: 10.10.27.200
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ka-ctl2:
          ansible_host: 10.10.27.201
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ka-ctl3:
          ansible_host: 10.10.27.202
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

    deployment:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
