# inventories/development/hosts.yml
---
all:
  children:
    # Core infrastructure groups
    control:
      hosts:
        ka-ctl1: &ctl1
          ansible_host: 10.10.27.200
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          kolla_api_interface_address: 10.10.27.200
        ka-ctl2: &ctl2
          ansible_host: 10.10.27.201
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          kolla_api_interface_address: 10.10.27.201
        ka-ctl3: &ctl3
          ansible_host: 10.10.27.202
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          kolla_api_interface_address: 10.10.27.202

    network:
      hosts:
        ka-net1: &net1
          ansible_host: 10.10.27.203
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ka-net2: &net2
          ansible_host: 10.10.27.204
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    compute:
      hosts:
        ka-hv1: &hv1
          ansible_host: 10.10.27.212
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        ka-hv2: &hv2
          ansible_host: 10.10.27.213
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    storage:
      hosts:
        ka-str1: &str1
          ansible_host: 10.10.27.206
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519

    # Bifrost (required by Kolla-Ansible conditionals)
    bifrost:
      hosts: {}

    # Essential Kolla-Ansible groups
    loadbalancer:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    monitoring:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Database groups
    # Database and Messaging
    mariadb:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    proxysql:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    rabbitmq:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Cache/session storage
    redis:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Keystone (Identity service)
    keystone:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Glance (Image service)
    glance-api:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    glance-registry:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Nova (Compute service)
    nova-api:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    nova-conductor:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    nova-novncproxy:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    nova-scheduler:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    nova-spicehtml5proxy:
      hosts: {}

    nova-serialproxy:
      hosts: {}

    nova-metadata:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    nova-super-conductor:
      hosts: {}

    # For Ironic integration
    nova-compute-ironic:
      hosts:
        ka-ctl1: *ctl1

    # Neutron (Networking service) - OVN configuration
    neutron-server:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    neutron-rpc-server:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    neutron-periodic-worker:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    neutron-ovn-maintenance-worker:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    neutron-ovn-metadata-agent:
      hosts:
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2

    neutron-dhcp-agent:
      hosts:
        ka-net1: *net1
        ka-net2: *net2

    neutron-l3-agent:
      hosts:
        ka-net1: *net1
        ka-net2: *net2

    neutron-metadata-agent:
      hosts:
        ka-net1: *net1
        ka-net2: *net2

    neutron-openvswitch-agent:
      hosts:
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2

    neutron-linuxbridge-agent:
      hosts: {}

    # Optional Neutron services
    neutron-bgp-dragent:
      hosts: {}

    neutron-infoblox-ipam-agent:
      hosts: {}

    neutron-metering-agent:
      hosts: {}

    neutron-ovn-agent:
      hosts: {}

    # Ironic-Neutron integration
    ironic-neutron-agent:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Ironic (Bare Metal service)
    ironic-api:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ironic-conductor:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ironic-inspector:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ironic-pxe:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ironic-tftp:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ironic-http:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ironic-dnsmasq:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ironic-prometheus-exporter:
      hosts: {}

    # Placement service
    placement-api:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Horizon (Dashboard)
    horizon:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Heat (Orchestration service) - optional
    heat-api:
      hosts: {}

    heat-api-cfn:
      hosts: {}

    heat-engine:
      hosts: {}

    # Cinder (Block Storage service) - using your storage node
    cinder-api:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    cinder-backup:
      hosts:
        ka-str1: *str1

    cinder-scheduler:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    cinder-volume:
      hosts:
        ka-str1: *str1

    # Additional infrastructure
    chrony:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2
        ka-str1: *str1

    cron:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    fluentd:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2
        ka-str1: *str1

    kolla-logs:
      hosts:
        ka-ctl1: *ctl1

    kolla-toolbox:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2
        ka-str1: *str1

    # Masakari (Instance High Availability)
    masakari-api:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    masakari-engine:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    masakari-instancemonitor:
      hosts:
        ka-hv1: *hv1
        ka-hv2: *hv2

    masakari-hostmonitor:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    hacluster:
      hosts: {}

    hacluster-remote:
      hosts: {}

    # Watcher (Resource Optimization)
    watcher-api:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    watcher-engine:
      hosts:
        ka-ctl1: *ctl1

    watcher-applier:
      hosts:
        ka-ctl1: *ctl1

    # Octavia (Load Balancer as a Service)
    octavia-api:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    octavia-health-manager:
      hosts:
        ka-net1: *net1
        ka-net2: *net2

    octavia-housekeeping:
      hosts:
        ka-ctl1: *ctl1

    octavia-worker:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    octavia-driver-agent:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Monitoring and Logging services
    prometheus:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    prometheus-mysqld-exporter:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    prometheus-memcached-exporter:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    prometheus-alertmanager:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    prometheus-openstack-exporter:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    prometheus-elasticsearch-exporter:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    prometheus-blackbox-exporter:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    prometheus-libvirt-exporter:
      hosts:
        ka-hv1: *hv1
        ka-hv2: *hv2

    grafana:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    elasticsearch:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    kibana:
      hosts:
        ka-ctl1: *ctl1

    # Add this group to your inventory
    openvswitch:
      hosts:
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2

    # OpenVSwitch services
    openvswitch-db-server:
      hosts:
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2

    openvswitch-vswitchd:
      hosts:
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2

    # OVN (Open Virtual Network) groups
    ovn-northd:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ovn-nb-db:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ovn-sb-db:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    ovn-controller:
      children:
        ovn-controller-compute: {}
        ovn-controller-network: {}

    ovn-controller-compute:
      hosts:
        ka-hv1: *hv1
        ka-hv2: *hv2

    ovn-controller-network:
      hosts:
        ka-net1: *net1
        ka-net2: *net2

    ovn-controller-vtep:
      hosts: {}

    # Additional common services that might be needed
    memcached:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    etcd:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    # Deployment host
    deployment:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    # Consolidated baremetal group (all physical hosts)
    baremetal:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2
        ka-str1: *str1

    prometheus-node-exporter:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2
        ka-str1: *str1

    # Add to your hosts.yml monitoring section
    prometheus-cadvisor:
      hosts:
        ka-net1: *net1
        ka-net2: *net2
        ka-hv1: *hv1
        ka-hv2: *hv2
        ka-str1: *str1

    opensearch:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    opensearch-dashboards:
      hosts:
        ka-ctl1: *ctl1

    skyline:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    skyline-apiserver:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3

    skyline-console:
      hosts:
        ka-ctl1: *ctl1
        ka-ctl2: *ctl2
        ka-ctl3: *ctl3
